const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.NSG_Isometric,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Browser,
		C3.Plugins.HTMLElement,
		C3.Plugins.NinePatch,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Spritefont2,
		C3.Behaviors.MoveTo,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.SpeedForID,
		C3.Plugins.Touch.Exps.TouchID,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Exps.AngleForID,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.NinePatch.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.JavaScriptInEvents.EventSheet2_Event20_Act1,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.Play
	];
};
self.C3_JsPropNameTable = [
	{health: 0},
	{maxHealth: 0},
	{speed: 0},
	{damage: 0},
	{attackSpeed: 0},
	{Tween: 0},
	{EasyIsometric: 0},
	{Player: 0},
	{xpValue: 0},
	{isPoisoned: 0},
	{Enemy: 0},
	{dirX: 0},
	{dirY: 0},
	{piercing: 0},
	{Bullet: 0},
	{Gem: 0},
	{HPBarBg: 0},
	{HPBarFill: 0},
	{ExpBarBg: 0},
	{ExpBarFill: 0},
	{LevelUpPanel: 0},
	{upgradeType: 0},
	{upgradeValue: 0},
	{weaponId: 0},
	{UpgradeButton: 0},
	{LevelText: 0},
	{KillCountText: 0},
	{TimerText: 0},
	{UpgradeText: 0},
	{Touch: 0},
	{Keyboard: 0},
	{Joystick: 0},
	{JoystickKnob: 0},
	{LevelIcon: 0},
	{LevelTextLobby: 0},
	{GoldIcon: 0},
	{GoldText: 0},
	{HeroesButton: 0},
	{HeroesButtonText: 0},
	{PlayButton: 0},
	{PlayButtonText: 0},
	{HeroNameText: 0},
	{HeroDescText: 0},
	{WeaponLabel: 0},
	{WeaponText: 0},
	{AbilityLabel: 0},
	{AbilityText: 0},
	{heroId: 0},
	{HeroCard: 0},
	{LockOverlay: 0},
	{SelectionFrame: 0},
	{ConfirmButton: 0},
	{ConfirmButtonText: 0},
	{BackButton: 0},
	{BackButtonText: 0},
	{TitleText: 0},
	{lifetime: 0},
	{SlashEffect: 0},
	{Sprite: 0},
	{TiledBackground: 0},
	{shadow: 0},
	{isBoss: 0},
	{Boss1: 0},
	{HPText: 0},
	{DamageVignette: 0},
	{Enemy2: 0},
	{goldValue: 0},
	{lootGold: 0},
	{Solid: 0},
	{Sprite3: 0},
	{Effects: 0},
	{DamageText: 0},
	{hpplusText: 0},
	{silverValue: 0},
	{lootSilver: 0},
	{silverCost: 0},
	{isOpened: 0},
	{Chest: 0},
	{Items: 0},
	{Weapons: 0},
	{Tomes: 0},
	{Enemy3: 0},
	{attackCooldown: 0},
	{isAttacking: 0},
	{attackTimer: 0},
	{hasFired: 0},
	{Enemy4: 0},
	{Enemy5: 0},
	{Enemy6: 0},
	{Enemy7: 0},
	{Sprite2: 0},
	{Gem2: 0},
	{progressFill2: 0},
	{Sprite4: 0},
	{silverCountBG: 0},
	{goldCountText: 0},
	{silverCountText: 0},
	{slot: 0},
	{weaponEquipped: 0},
	{TooltipText: 0},
	{weaponEquippedResponsive: 0},
	{m: 0},
	{RESPONSIVE: 0},
	{Browser: 0},
	{dark: 0},
	{StatsButton: 0},
	{StatsBtnText: 0},
	{StatsOverlay: 0},
	{StatsPanel: 0},
	{isCloseButton: 0},
	{StatsCloseButton: 0},
	{StatsText: 0},
	{StatsScrollable: 0},
	{"NAME📌": 0},
	{"DIRECTION_DOWN📌": 0},
	{listTotHeight: 0},
	{listTotHehight2: 0},
	{"9patchchours": 0},
	{"PARENT_NAME📌": 0},
	{touchyinit: 0},
	{touchspeed: 0},
	{slidepos: 0},
	{slideinitialvelocityu: 0},
	{scrolling: 0},
	{piny: 0},
	{pinylimit: 0},
	{yyy: 0},
	{yyyy: 0},
	{choruspin: 0},
	{list: 0},
	{closelist: 0},
	{textEffects: 0},
	{Energy: 0},
	{Enemy8: 0},
	{slotbg: 0},
	{Sprite5: 0},
	{hpplusText2: 0},
	{bg: 0},
	{Sprite6: 0},
	{activetab: 0},
	{hpplusText3: 0},
	{hpplusText4: 0},
	{Sprite7: 0},
	{characterPortraits: 0},
	{ToolTip2: 0},
	{TooltipText2: 0},
	{buyButton: 0},
	{priceText: 0},
	{lock: 0},
	{buyText: 0},
	{close: 0},
	{buttonsettings: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{xx: 0},
	{yy: 0},
	{w: 0},
	{settingsclosebutton: 0},
	{buttonsettings2: 0},
	{exitbutton: 0},
	{resetbutton: 0},
	{tapto: 0},
	{buttonsettings3: 0},
	{ww: 0},
	{hh: 0},
	{spriteTextmessage: 0},
	{deleteprogress: 0},
	{type: 0},
	{giftTXT3: 0},
	{yes: 0},
	{no: 0},
	{tapto2: 0},
	{Claim: 0},
	{victory: 0},
	{HPBarBg2: 0},
	{HPBarFill2: 0},
	{HPText2: 0},
	{defeat: 0},
	{"9p_Back": 0},
	{MoveTo: 0},
	{sp_Pin: 0},
	{delete: 0},
	{layer: 0},
	{opacity: 0},
	{x: 0},
	{y: 0},
	{Grid_size: 0},
	{ScrollYLimit: 0},
	{CurrentNAME: 0},
	{fxMuted: 0},
	{musicMuted: 0},
	{audioName: 0},
	{Loop: 0},
	{v: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Bullet: class extends self.ISpriteInstance {},
	Gem: class extends self.ISpriteInstance {},
	HPBarBg: class extends self.ISpriteInstance {},
	HPBarFill: class extends self.ISpriteInstance {},
	ExpBarBg: class extends self.ISpriteInstance {},
	ExpBarFill: class extends self.ISpriteInstance {},
	LevelUpPanel: class extends self.ISpriteInstance {},
	UpgradeButton: class extends self.ISpriteInstance {},
	LevelText: class extends self.ITextInstance {},
	KillCountText: class extends self.ITextInstance {},
	TimerText: class extends self.ITextInstance {},
	UpgradeText: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Joystick: class extends self.ISpriteInstance {},
	JoystickKnob: class extends self.ISpriteInstance {},
	LevelIcon: class extends self.ISpriteInstance {},
	LevelTextLobby: class extends self.ITextInstance {},
	GoldIcon: class extends self.ISpriteInstance {},
	GoldText: class extends self.ITextInstance {},
	HeroesButton: class extends self.ISpriteInstance {},
	HeroesButtonText: class extends self.ITextInstance {},
	PlayButton: class extends self.ISpriteInstance {},
	PlayButtonText: class extends self.ITextInstance {},
	HeroNameText: class extends self.ITextInstance {},
	HeroDescText: class extends self.ITextInstance {},
	WeaponLabel: class extends self.ITextInstance {},
	WeaponText: class extends self.ITextInstance {},
	AbilityLabel: class extends self.ITextInstance {},
	AbilityText: class extends self.ITextInstance {},
	HeroCard: class extends self.ISpriteInstance {},
	LockOverlay: class extends self.ISpriteInstance {},
	SelectionFrame: class extends self.ISpriteInstance {},
	ConfirmButton: class extends self.ISpriteInstance {},
	ConfirmButtonText: class extends self.ITextInstance {},
	BackButton: class extends self.ISpriteInstance {},
	BackButtonText: class extends self.ITextInstance {},
	TitleText: class extends self.ITextInstance {},
	SlashEffect: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	shadow: class extends self.ISpriteInstance {},
	Boss1: class extends self.ISpriteInstance {},
	HPText: class extends self.ITextInstance {},
	DamageVignette: class extends self.ISpriteInstance {},
	Enemy2: class extends self.ISpriteInstance {},
	lootGold: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Effects: class extends self.ISpriteInstance {},
	DamageText: class extends self.ITextInstance {},
	hpplusText: class extends self.ITextInstance {},
	lootSilver: class extends self.ISpriteInstance {},
	Chest: class extends self.ISpriteInstance {},
	Items: class extends self.ISpriteInstance {},
	Weapons: class extends self.ISpriteInstance {},
	Tomes: class extends self.ISpriteInstance {},
	Enemy3: class extends self.ISpriteInstance {},
	Enemy4: class extends self.ISpriteInstance {},
	Enemy5: class extends self.ISpriteInstance {},
	Enemy6: class extends self.ISpriteInstance {},
	Enemy7: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Gem2: class extends self.ISpriteInstance {},
	progressFill2: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	silverCountBG: class extends self.ISpriteInstance {},
	goldCountText: class extends self.ITextInstance {},
	silverCountText: class extends self.ITextInstance {},
	weaponEquipped: class extends self.ISpriteInstance {},
	TooltipText: class extends self.ITextInstance {},
	weaponEquippedResponsive: class extends self.ISpriteInstance {},
	RESPONSIVE: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	dark: class extends self.ISpriteInstance {},
	StatsButton: class extends self.ISpriteInstance {},
	StatsBtnText: class extends self.ITextInstance {},
	StatsOverlay: class extends self.ISpriteInstance {},
	StatsPanel: class extends self.ISpriteInstance {},
	StatsCloseButton: class extends self.ISpriteInstance {},
	StatsText: class extends self.ITextInstance {},
	StatsScrollable: class extends self.IHTMLElementInstance {},
	_9patchchours: class extends self.I9PatchInstance {},
	choruspin: class extends self.ISpriteInstance {},
	list: class extends self.ISpriteInstance {},
	closelist: class extends self.ISpriteInstance {},
	textEffects: class extends self.ISpriteInstance {},
	Energy: class extends self.ISpriteInstance {},
	Enemy8: class extends self.ISpriteInstance {},
	slotbg: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	hpplusText2: class extends self.ITextInstance {},
	bg: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	activetab: class extends self.ISpriteInstance {},
	hpplusText3: class extends self.ITextInstance {},
	hpplusText4: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	characterPortraits: class extends self.ISpriteInstance {},
	ToolTip2: class extends self.ISpriteInstance {},
	TooltipText2: class extends self.ITextInstance {},
	buyButton: class extends self.ISpriteInstance {},
	priceText: class extends self.ITextInstance {},
	lock: class extends self.ISpriteInstance {},
	buyText: class extends self.ITextInstance {},
	close: class extends self.ISpriteInstance {},
	buttonsettings: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	settingsclosebutton: class extends self.ISpriteInstance {},
	buttonsettings2: class extends self.ISpriteInstance {},
	exitbutton: class extends self.ISpriteInstance {},
	resetbutton: class extends self.ISpriteInstance {},
	tapto: class extends self.ITextInstance {},
	buttonsettings3: class extends self.ISpriteInstance {},
	spriteTextmessage: class extends self.ISpriteFontInstance {},
	deleteprogress: class extends self.ISpriteInstance {},
	giftTXT3: class extends self.ITextInstance {},
	yes: class extends self.ISpriteInstance {},
	no: class extends self.ISpriteInstance {},
	tapto2: class extends self.ITextInstance {},
	Claim: class extends self.ISpriteInstance {},
	victory: class extends self.ISpriteInstance {},
	HPBarBg2: class extends self.ISpriteInstance {},
	HPBarFill2: class extends self.ISpriteInstance {},
	HPText2: class extends self.ITextInstance {},
	defeat: class extends self.ISpriteInstance {},
	_9p_Back: class extends self.I9PatchInstance {},
	sp_Pin: class extends self.ISpriteInstance {}
}